import type { Metadata } from "next";
import { Geist, Geist_Mono, Onest, Poppins } from "next/font/google";
import "./globals.css";
// import SmoothScroll from "@/components/ui/smooth-scroll";
import ContextProvider from "@/context/ContextProvider";
import Initialization from "./Initialization";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const poppins = Poppins({
    variable: "--fonts-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify font weights
    subsets: ["latin"], // Subsets to include
    style: ["normal", "italic"], // Optional
    display: "swap", // Recommended for better loading behavior
});

const onest = Onest({
    variable: "--fonts-onest",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify font weights
    subsets: ["latin"], // Subsets to include
    style: ["normal"], // Optional
    display: "swap", // Recommended for better loading behavior
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${onest.variable} antialiased bkg-layer`}
            >
                <ContextProvider>
                    {/* <SmoothScroll></SmoothScroll> */}
                    {children}
                    <Initialization />
                </ContextProvider>
            </body>
        </html>
    );
}
